const colors = ["#ef4444", "#22c55e", "#facc15", "#3b82f6"];
const names = ["लाल", "हरा", "पीला", "नीला"];
const board = document.querySelector('#board');
const state = { players: 4, winTarget: 4, turn: 0, roll: null, pieces: [], config: [], theme: 'sunset', mode: 'computer', gameOver: false, aiPending: false };

const route = [
  [6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[7,14],
  [8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[7,0],
  [6,0]
];
const homePaths = [ [[7,1],[7,2],[7,3],[7,4],[7,5]], [[1,7],[2,7],[3,7],[4,7],[5,7]], [[7,13],[7,12],[7,11],[7,10],[7,9]], [[13,7],[12,7],[11,7],[10,7],[9,7]] ];
const homes = [ [[1,1],[1,4],[4,1],[4,4]], [[1,10],[1,13],[4,10],[4,13]], [[10,1],[10,4],[13,1],[13,4]], [[10,10],[10,13],[13,10],[13,13]] ];
const starts = [0, 13, 26, 39];
const themeMap = { sunset:['#fff7ed','#ef4444','#fee2e2'], ocean:['#eff6ff','#0284c7','#dbeafe'], mint:['#ecfdf5','#059669','#d1fae5'], midnight:['#0f172a','#8b5cf6','#1e293b'] };

function setTheme() { const [bg,accent,soft] = themeMap[state.theme]; document.documentElement.style.setProperty('--bg',bg); document.documentElement.style.setProperty('--accent',accent); document.documentElement.style.setProperty('--accent-soft',soft); document.documentElement.style.setProperty('--card',state.theme==='midnight'?'#f8fafc':'#fff'); }
function initConfig() { state.config = Array.from({length: state.players}, (_,i)=>({name:names[i],color:colors[i]})); renderPlayerSettings(); }
function renderPlayerSettings() { document.querySelector('#playerSettings').innerHTML = state.config.map((p,i)=>`<div class="player-row"><label>खिलाड़ी ${i+1}<input data-name="${i}" value="${p.name}" /></label><label><input class="color-input" data-color="${i}" type="color" value="${p.color}" aria-label="रंग" /></label></div>`).join(''); }
function newGame() { state.turn=0; state.roll=null; state.gameOver=false; state.pieces=state.config.flatMap((_,p)=>Array.from({length:4},(_,id)=>({p,id,progress:-1}))); render(); }
function cellKey(r,c) { return `${r}-${c}`; }
function getPosition(piece) { if(piece.progress < 0) return homes[piece.p][piece.id]; if(piece.progress < 51) return route[(starts[piece.p]+piece.progress)%52]; if(piece.progress < 56) return homePaths[piece.p][piece.progress-51]; return [7,7]; }
function render() {
  setTheme(); board.innerHTML=''; const pathKeys=new Set(route.map(p=>cellKey(...p))); const startMap=new Map(starts.map((s,i)=>[cellKey(...route[s]),i]));
  for(let r=0;r<15;r++) for(let c=0;c<15;c++) { const key=cellKey(r,c); const cell=document.createElement('div'); cell.className='cell'; const zonePlayer = r<6&&c<6?0:r<6&&c>8?1:r>8&&c<6?3:r>8&&c>8?2:-1; const homePathPlayer=homePaths.findIndex(group=>group.some(x=>x[0]===r&&x[1]===c)); const homeSlot=homes.findIndex(group=>group.some(x=>x[0]===r&&x[1]===c)); if(pathKeys.has(key)) cell.classList.add('path'); if(zonePlayer>=0){cell.classList.add('home-zone');cell.style.setProperty('--cell-color',state.config[zonePlayer]?.color||'#e2e8f0');} if(homeSlot>=0) cell.classList.add('home-slot'); if(homePathPlayer>=0){cell.classList.add('home-path');cell.style.setProperty('--cell-color',state.config[homePathPlayer]?.color||'#e2e8f0');} if(startMap.has(key)){cell.classList.add('start');cell.style.setProperty('--cell-color',state.config[startMap.get(key)]?.color||'#e2e8f0');} if(r===7&&c===7) cell.classList.add('center'); cell.dataset.key=key; board.append(cell); }
  state.pieces.forEach(piece=> { const [r,c]=getPosition(piece); const cell=board.querySelector(`[data-key="${cellKey(r,c)}"]`); const token=document.createElement('button'); token.className='piece'; token.style.setProperty('--piece-color',state.config[piece.p].color); token.title=`${state.config[piece.p].name} की गोटी`; token.onclick=()=>movePiece(piece); if(canMove(piece)) token.classList.add('movable'); cell.append(token); }); updateStatus();
}
function canMove(piece) { if(state.gameOver||state.roll===null||piece.p!==state.turn) return false; if(piece.progress===-1) return state.roll===1||state.roll===6; return piece.progress+state.roll<=56; }
function rollDice() { if(state.roll!==null||state.gameOver||state.aiPending) return; state.roll=Math.floor(Math.random()*6)+1; document.querySelector('#diceText').textContent=`पासा: ${state.roll}`; const moves=state.pieces.filter(canMove); if(!moves.length){ document.querySelector('#hint').textContent='कोई चाल नहीं—अगले खिलाड़ी की बारी।'; setTimeout(nextTurn,700); } else { document.querySelector('#hint').textContent=state.mode==='computer'&&state.turn>0?'कंप्यूटर चाल चल रहा है…':'चलने वाली गोटी पर क्लिक करें।'; render(); if(state.mode==='computer'&&state.turn>0){ state.aiPending=true; setTimeout(()=>{const options=state.pieces.filter(canMove); const best=options.sort((a,b)=>b.progress-a.progress)[0]; state.aiPending=false; if(best) movePiece(best);},700); } } }
function movePiece(piece) { if(!canMove(piece)) return; piece.progress = piece.progress===-1 ? 0 : piece.progress+state.roll; if(piece.progress<51){ const [r,c]=getPosition(piece); state.pieces.forEach(other=>{ if(other.p!==piece.p && other.progress>=0 && other.progress<51 && cellKey(...getPosition(other))===cellKey(r,c) && !starts.includes((starts[piece.p]+piece.progress)%52)) other.progress=-1; }); } if(state.pieces.filter(x=>x.p===piece.p&&x.progress===56).length>=state.winTarget){ state.gameOver=true; document.querySelector('#hint').textContent=`🎉 ${state.config[piece.p].name} जीत गया!`; render(); return; } if(state.roll===6){ state.roll=null; document.querySelector('#hint').textContent='6 आया—फिर से पासा फेंकें।'; render(); } else nextTurn(); }
function nextTurn(){ state.roll=null; state.turn=(state.turn+1)%state.players; document.querySelector('#hint').textContent=state.mode==='friends'?'फोन अगले खिलाड़ी को दें और पासा फेंकें।':'पासा फेंकें।'; render(); if(state.mode==='computer'&&state.turn>0) setTimeout(rollDice,500); }
function updateStatus(){ const p=state.config[state.turn]; const displayName=state.mode==='computer'&&state.turn>0?`कंप्यूटर (${p.name})`:p.name; document.querySelector('#statusText').textContent=state.gameOver?'गेम समाप्त':`${displayName} खिलाड़ी की बारी`; document.querySelector('#turnDot').style.background=p.color; document.querySelector('#diceText').textContent=state.roll?`पासा: ${state.roll}`:'पासा फेंकें'; document.querySelector('#rollBtn').disabled=state.roll!==null||state.gameOver||state.aiPending||(state.mode==='computer'&&state.turn>0); }
document.querySelector('#rollBtn').onclick=rollDice; document.querySelector('#newGameBtn').onclick=newGame;
document.querySelector('#playersInput').onchange=e=>{ const n=Math.max(2,Math.min(4,+e.target.value||4)); state.players=n; initConfig(); };
document.querySelector('#applyBtn').onclick=()=>{ state.config.forEach((p,i)=>{p.name=document.querySelector(`[data-name="${i}"]`).value.trim()||names[i];p.color=document.querySelector(`[data-color="${i}"]`).value;}); state.winTarget=Math.max(1,Math.min(4,+document.querySelector('#winInput').value||4)); state.theme=document.querySelector('#themeSelect').value; state.mode=document.querySelector('#modeSelect').value; document.querySelector('#gameTitle').textContent=document.querySelector('#titleInput').value.trim()||'Ludo Studio'; newGame(); };
initConfig(); newGame();
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => {});
